name: CI - master

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  deploy:
    runs-on:
      ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 12

      - name: install dependencies
        run: npm ci

      - name: frontend build
        run: npm run build

      - name: Authenticate to google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          export_environment_variables: true
          create_credentials_file: true
          credentials_json: ${{ secrets.GCP_API_KEY }}

      - name: Setup gcloud
        id: setup-gcloud
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ inputs.project_id }}
          service_account_key: ${{ secrets.GCP_API_KEY }}
          export_default_credentials: true

      - name: Deploy and serve frontend
        run: |-
          gsutil -m rsync -R -d ./dist/knight-npc-generator gs://kng-frontend
          gsutil setmeta -h "Cache-Control:no-store" gs://kng-frontend/index.html
  